//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurent
    {
        public int Id_restaurant { get; set; }
        public string Name_restaurant { get; set; }
        public string Description_restaurant { get; set; }
        public string Image_restaurant { get; set; }
    }
}
