//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [DisplayName("Id")]
        public int RegId { get; set; }
        [DisplayName("Nom et prenom")]
        public string Name { get; set; }
        [DisplayName("Nom d'utilisateur")]
        [Required(ErrorMessage = "ce champ est obligatoire")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "ce champ est obligatoire")]
        [DataType(DataType.Password)]
        [DisplayName("Mot de passe")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Confirmer Mot de passe")]
        [Compare("Password", ErrorMessage = "Les deux mot de passe ne sont pas identiques")]
        public string ConfirmPassword { get; set; }
        [DisplayName("Admin")]

        public bool IsAdmin { get; set; }
        public string LoginErrorMessage { get; set; }
        [DisplayName("Upload your image")]

        public string image { get; set; }
    }
}
